server:
  port: 9090
mpesa:
  daraja:
    consumer-key: ${env.CONSUMER_KEY}
    consumer-secret: ${env.CONSUMER_SECRET}
    grant-type: client_credentials
    oauth-endpoint: https://sandbox.safaricom.co.ke/oauth/v1/generate
    register-url-endpoint: https://sandbox.safaricom.co.ke/mpesa/c2b/v1/registerurl
    simulate-transaction-endpoint: https://sandbox.safaricom.co.ke/mpesa/c2b/v1/simulate
    shortCode: 601426
    responseType: Completed
    confirmation-url: https://274e-196-111-83-125.ngrok-free.app/mobile-money/confirmation
    validation-url: https://274e-196-111-83-125.ngrok-free.app/mobile-money/validation
    b2c-transaction-endpoint: https://sandbox.safaricom.co.ke/mpesa/b2c/v1/paymentrequest
    b2c-result-url: https://274e-196-111-83-125.ngrok-free.app/mobile-money/b2c-transaction-result
    b2c-queue-timeout-url: https://274e-196-111-83-125.ngrok-free.app/mobile-money/b2c-queue-timeout-url
    b2c-initiator-name: testapi
    b2c-initiator-password: Safaricom999!*!
